"""
models.py
=========
Domain model for the blog post entity in the SQLAlchemy/PostgreSQL example.

``Post`` is a pure-Python ``@dataclass`` subclass of ``DomainModel``.
No ORM imports, no SQLAlchemy Session — the ``varco_sa`` backend generates
the full ORM mapping at startup via ``SAModelFactory`` from the field
annotations and ``FieldHint`` / ``PrimaryKey`` metadata decorators.

Key design choices
------------------
- ``pk`` uses ``PKStrategy.UUID_AUTO`` — the repository generates a UUID
  Python-side before INSERT, so the ``pk`` is available immediately after
  ``save()`` without a SELECT round-trip.
- ``created_at`` / ``updated_at`` are stamped Python-side in the service
  hook (``_prepare_for_create`` / ``apply_update``) rather than relying on
  database ``DEFAULT NOW()`` expressions.  This makes the values readable
  in tests without waiting for a DB round-trip.
- ``author`` is a plain ``str`` (display name, not a foreign key) so the
  example stays self-contained — no ``User`` table needed.

DESIGN: Pure DomainModel with no ORM imports
    ✅ Models are backend-agnostic — the same class works with SA, Beanie, etc.
    ✅ No ORM code in tests — instantiate ``Post(title=..., body=..., author=...)``
       directly without a session.
    ✅ ``SAModelFactory`` auto-generates the ORM class from the annotations —
       no manual ``Column()`` declarations needed.
    ❌ No back-references or SA relationships — those require post-build
       ``SAModelRegistry.get()`` customisation (acceptable here).

Thread safety:  ✅ Dataclass — no shared mutable state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PrimaryKey, PKStrategy, pk_field
from varco_core.model import DomainModel


@dataclass
class Post(DomainModel):
    """
    Blog post domain entity.

    The ORM mapping is generated automatically by ``SAModelFactory`` at
    application startup from the field annotations below.

    Fields:
        pk:         UUID primary key, auto-generated on INSERT.
        title:      Post headline, max 255 chars.
        body:       Post body text — stored as TEXT (no length limit in the DB).
        author:     Author display name, max 120 chars.
        created_at: UTC timestamp set by the service hook on INSERT.
        updated_at: UTC timestamp set by the service hook on INSERT and UPDATE.

    Edge cases:
        - ``pk`` is ``None`` until the entity is persisted.  ``PostRead.pk``
          is always populated — the assembler only calls ``to_read_dto()``
          on persisted entities.
        - ``created_at`` and ``updated_at`` default to ``None`` until
          ``PostService._prepare_for_create()`` stamps them.

    Thread safety:  ✅ Dataclass — no shared state.
    Async safety:   ✅ Pure value object.
    """

    # Primary key — UUID auto-generated by the repository before INSERT.
    # pk_field(init=False) means the constructor does not accept pk — the
    # mapper assigns it from the ORM object after flush.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    # Business fields — FieldHint() carries column metadata for SAModelFactory.
    title: Annotated[str, FieldHint(max_length=255)] = ""
    body: Annotated[str, FieldHint()] = ""
    author: Annotated[str, FieldHint(max_length=120)] = ""

    # Server-managed timestamps — stamped Python-side in PostService hooks.
    # Both default to None because they are not set in the constructor —
    # they are populated before save() is called in _prepare_for_create().
    created_at: Annotated[datetime | None, FieldHint(nullable=True)] = None
    updated_at: Annotated[datetime | None, FieldHint(nullable=True)] = None

    class Meta:
        # Table name in the PostgreSQL database.
        # Prefixed with "ex09_" to avoid collisions if other examples run
        # against the same database cluster.
        table = "ex09_posts"


__all__ = ["Post"]
