"""
varco_fastapi.client.stubs
=============================
``.pyi`` stub emitter for a ``ServiceContract`` (Plan 009, Phase 7 / C2).

Gives mypy/IDEs real static types for a ``client_for()``-built client without
requiring the service to be importable — the stub is generated once (at CI
time, via ``varco gen-client-stubs``, Phase 8) and checked into the consuming
repo alongside the exported ``.contract.json``.

DESIGN: ``.pyi`` stubs over runtime-only typing
    ✅ mypy/IDEs see real, static types with no service import required.
    ❌ A generation step that can drift from the contract — mitigated by
       ``varco gen-client-stubs --check`` (Phase 8), which re-renders and
       diffs rather than trusting a stale file.

Thread safety:  ✅ Pure functions.
Async safety:   ✅ No I/O in ``render_stub``; ``write_stub`` does a plain
                   synchronous file write (CLI-only usage, no event loop).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def render_stub(contract: Any, *, class_name: str) -> str:
    """
    Render a ``.pyi`` stub for ``contract``.

    Args:
        contract:   A ``ServiceContract``.
        class_name: Name of the generated client class in the stub.

    Returns:
        Valid Python source (parseable via ``ast.parse``) declaring
        ``class {class_name}(AsyncVarcoClient): ...`` with one method
        stub per route.
    """
    lines: list[str] = [
        "# Auto-generated by varco gen-client-stubs — DO NOT EDIT.",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from varco_fastapi.client import AsyncVarcoClient",
        "",
        "",
        f"class {class_name}(AsyncVarcoClient):",
    ]

    if not contract.routes:
        lines.append("    ...")
        return "\n".join(lines) + "\n"

    for route in contract.routes:
        params = ["self"]
        body_params = [p for p in route.params if p.kind == "body"]
        other_params = [p for p in route.params if p.kind != "body"]
        for p in body_params:
            params.append(f"{p.name}: Any" if p.required else f"{p.name}: Any = ...")
        if other_params or route.async_capable:
            params.append("*")
            for p in other_params:
                params.append(
                    f"{p.name}: Any" if p.required else f"{p.name}: Any = ..."
                )
            if route.async_capable:
                params.append("with_async: bool = ...")

        sig = ", ".join(params)
        lines.append(f"    async def {route.name}({sig}) -> Any: ...")

    return "\n".join(lines) + "\n"


def write_stub(contract: Any, path: Path, *, class_name: str) -> None:
    """Render and write a ``.pyi`` stub to ``path`` (parent dirs must exist)."""
    Path(path).write_text(render_stub(contract, class_name=class_name))


__all__ = ["render_stub", "write_stub"]
