"""
models
======
Domain model for the ``Product`` entity.

``Product`` is a pure-Python ``@dataclass`` — no ORM imports, no session
references.  It uses ``AuditedDomainModel`` so ``created_at`` and
``updated_at`` are available on every persisted entity.

DESIGN: ``AuditedDomainModel`` over plain ``DomainModel``
    ✅ ``created_at`` / ``updated_at`` are automatically available — no manual
       timestamp management in assembler or repo.
    ✅ ``ProductRead`` can declare those fields as required without extra checks.
    ❌ Two extra fields on every instance — negligible overhead for a demo.

Thread safety:  ✅ Dataclass — no shared mutable state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PKStrategy, PrimaryKey, pk_field
from varco_core.model import AuditedDomainModel


@dataclass
class Product(AuditedDomainModel):
    """
    Product catalog entity.

    Fields:
        pk:          UUID, auto-generated by the in-memory repository on save().
        name:        Product display name, max 255 chars.
        description: Optional product description.
        price:       Unit price — must be non-negative in practice, but
                     domain-level validation is intentionally omitted to
                     keep this example minimal.
        in_stock:    Whether the product is currently available.
        created_at:  UTC timestamp set on first save() — inherited from
                     ``AuditedDomainModel``.
        updated_at:  UTC timestamp refreshed on every save() — inherited
                     from ``AuditedDomainModel``.

    Edge cases:
        - ``pk`` is ``None`` until persisted.  The in-memory repository assigns
          a UUID on first ``save()`` via ``object.__setattr__``.
        - ``created_at`` / ``updated_at`` are also ``None`` until persisted —
          the repository sets them; assembler must not read them before save().

    Thread safety:  ✅ Dataclass — each instance is independent.
    Async safety:   ✅ Pure value object — no I/O.
    """

    # Primary key — UUID auto-generated by the repository on first save().
    # ``pk_field()`` sets ``init=False`` so the constructor does not accept
    # pk as an argument; the repo assigns it via ``object.__setattr__``.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    name: Annotated[str, FieldHint(max_length=255)] = ""
    description: str = ""
    price: float = 0.0
    in_stock: bool = True

    class Meta:
        table = "products"


__all__ = ["Product"]
