"""
models
======
Domain model for the ``Document`` entity.

``Document`` uses ``AuditedDomainModel`` for automatic timestamp management
(``created_at`` / ``updated_at``) and carries an ``owner_id`` field so the
``OwnershipAuthorizer`` can check document ownership without a DB join.

DESIGN: ``owner_id`` on the domain model vs. a separate permissions table
    ✅ Zero-latency ownership check — the ``authorize()`` call reads a field
       already loaded from the repository, no extra query needed.
    ✅ Works with ``OwnershipAuthorizer`` out of the box — no custom override.
    ✅ Audit trail: owner is stored with the document, survives user deletion.
    ❌ Ownership transfer requires updating ``owner_id`` — add an explicit
       ``transfer_ownership`` service method if that is needed.

Thread safety:  ✅ Dataclass — each instance is independent, no shared state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PKStrategy, PrimaryKey, pk_field
from varco_core.model import AuditedDomainModel


@dataclass
class Document(AuditedDomainModel):
    """
    Document entity — the core resource managed by this example.

    Fields:
        pk:         UUID, auto-generated by the repository on first ``save()``.
        title:      Document title, max 255 chars.
        content:    Document body (freeform text).
        owner_id:   Subject identifier of the creator — set by the service
                    in ``_prepare_for_create`` from ``ctx.user_id``.  Used by
                    ``OwnershipAuthorizer`` for DELETE access control.
        created_at: UTC timestamp set on first ``save()`` — inherited.
        updated_at: UTC timestamp refreshed on every ``save()`` — inherited.

    Edge cases:
        - ``pk`` is ``None`` until persisted.
        - ``owner_id`` is ``None`` until ``_prepare_for_create`` stamps it.
          The repo never assigns it — the service is responsible.
        - ``created_at`` / ``updated_at`` are ``None`` until after the first
          ``save()`` — the assembler must not read them before save returns.

    Thread safety:  ✅ Dataclass — immutable after construction.
    Async safety:   ✅ Pure value object — no I/O.
    """

    # Primary key — UUID auto-generated by the repository on first save().
    # ``pk_field()`` marks this as ``init=False`` so the constructor does not
    # accept it; the repository stamps it via ``object.__setattr__``.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    title: Annotated[str, FieldHint(max_length=255)] = ""
    content: str = ""

    # Owner subject — stamped by DocumentService._prepare_for_create() from
    # ctx.user_id.  None until creation completes; never None after save().
    # OwnershipAuthorizer reads this field by name ("owner_id") for DELETE checks.
    owner_id: str | None = None

    class Meta:
        table = "documents"


__all__ = ["Document"]
