"""
models
======
Domain model for the ``Post`` entity used in the observability-metrics example.

``Post`` is a pure-Python ``@dataclass`` — no ORM imports, no session
references.  It uses ``AuditedDomainModel`` so ``created_at`` and
``updated_at`` are automatically populated by the in-memory repository.

DESIGN: ``AuditedDomainModel`` over plain ``DomainModel``
    ✅ ``created_at`` / ``updated_at`` fields are inherited — no manual
       timestamp logic in the assembler or repository.
    ✅ Keeps the example self-consistent with 01-minimal-crud-api so readers
       can compare patterns across examples.
    ❌ Two extra fields on every instance — negligible overhead for a demo.

Thread safety:  ✅ Dataclass — no shared mutable state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PKStrategy, PrimaryKey, pk_field
from varco_core.model import AuditedDomainModel


@dataclass
class Post(AuditedDomainModel):
    """
    Blog post entity.

    Used in the observability-metrics example to give the ASGI app real routes
    to exercise so the ``MetricsMiddleware`` has something to measure.

    Fields:
        pk:          UUID, auto-generated by the in-memory repository on first
                     ``save()``.
        title:       Post title, max 255 chars.
        body:        Post body text; may be empty.
        published:   Whether the post is publicly visible.
        created_at:  UTC timestamp set on first ``save()`` — inherited from
                     ``AuditedDomainModel``.
        updated_at:  UTC timestamp refreshed on every ``save()`` — inherited
                     from ``AuditedDomainModel``.

    Edge cases:
        - ``pk`` is ``None`` until persisted.  The in-memory repository assigns
          a UUID on first ``save()`` via ``object.__setattr__``.
        - ``created_at`` / ``updated_at`` are also ``None`` until persisted.
          Do not read them before the entity has been saved.

    Thread safety:  ✅ Dataclass — each instance is independent.
    Async safety:   ✅ Pure value object — no I/O.
    """

    # Primary key — UUID auto-generated by the repository on first save().
    # ``pk_field()`` sets ``init=False`` so the constructor does not accept pk
    # as an argument; the repository assigns it via ``object.__setattr__``.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    title: Annotated[str, FieldHint(max_length=255)] = ""
    body: str = ""
    published: bool = False

    class Meta:
        table = "posts"


__all__ = ["Post"]
