"""
varco_core.asyncapi.generator
==============================
Build an **AsyncAPI 3.1.0** document from *live, wired* ``EventConsumer``
instances (Plan 022 §D-AA1–§D-AA3, Plan 030 / Phase 1).

The mapping is direct and total:

===========================  =================================================
varco                        AsyncAPI 3.1.0
===========================  =================================================
``@listen``'s channel        a **channel** (its ``address``)
the decorated handler        an **operation**, ``action: receive``
the ``Event`` subclass       a **message**, payload from ``model_json_schema()``
===========================  =================================================

DESIGN: generate at RUNTIME from wired instances, never a static import walk
    ✅ ``@listen``'s channel may be ``Callable[[Any], str]``
       (``event/consumer.py``'s ``_ListenEntry.channel``), resolved at
       ``register_to()`` time against a bound ``self`` — a static scan reports the
       lambda, or one channel for two differently configured instances, and is
       silently wrong.
    ✅ Reuses the exact metadata ``register_to()`` consumes, so the document
       cannot describe a wiring that does not exist.
    ❌ The caller must import and construct the app.  Identical cost to FastAPI's
       own ``openapi.json`` export, and familiar for that reason.
    ❌ A consumer that was never registered is never documented.  That is correct
       behaviour, and it is asserted by a unit test so it reads as intentional.

DESIGN: emit a plain ``dict``, serialize with ``json`` — no AsyncAPI library
    ✅ Zero new runtime dependency in ``varco_core`` (the standing repo rule).
       Research 004 §2: there is no Python library that *produces* AsyncAPI, and
       ``datamodel-code-generator`` — the risk the backlog flagged — consumes
       schemas rather than producing documents.
    ✅ Pydantic v2 emits JSON Schema Draft 2020-12, which AsyncAPI 3.x accepts.
    ❌ varco owns conformance to the AsyncAPI schema.  Mitigated by the committed
       snapshot + ``varco export-asyncapi --check`` gate and one recorded
       ``npx @asyncapi/cli validate`` run (§D-AA4).

Thread safety:  ✅ Pure function over the objects handed to it; no shared state.
Async safety:   ✅ No I/O and no ``await`` — safe to call from any context.

📚 Docs
- 📘 https://www.asyncapi.com/docs/reference/specification/v3.1.0
  AsyncAPI 3.1.0 — channels / operations / messages
- 📘 https://github.com/asyncapi/bindings/tree/master/kafka
  Kafka bindings 0.5.0 — ``topic`` (channel), ``groupId``/``clientId`` (operation)
"""

from __future__ import annotations

import inspect
import re
from typing import TYPE_CHECKING, Any
from urllib.parse import urlsplit

from providify import DIContainer

from varco_core.event.base import Event
from varco_core.event.consumer import EventConsumer

if TYPE_CHECKING:  # pragma: no cover — typing only
    from collections.abc import Iterable, Mapping

    from varco_core.event.consumer import _ListenEntry

#: The spec version this generator targets.  Research 004 §2 and §D-AA1 agree on
#: 3.1.0; RS-3 reserved the module name for exactly this.
ASYNCAPI_VERSION = "3.1.0"

#: Binding-specification versions.  Both are REQUIRED fields inside their own
#: binding object — a binding stanza without one is invalid, not merely terse.
_KAFKA_BINDING_VERSION = "0.5.0"
_NATS_BINDING_VERSION = "0.1.0"

# Document keys are free-form, but they are also JSON-Pointer path segments in
# every `$ref` — so anything needing pointer escaping (`/`, `~`) is replaced.
_KEY_SAFE_RE = re.compile(r"[^A-Za-z0-9_.\-]")

#: Explains, inside the artifact itself, why some protocols carry bindings and
#: others do not — so a reader wondering about their empty Redis channels finds
#: the answer here rather than in a plan file (§D-AA3).
_BINDING_COVERAGE_NOTE = (
    "Binding coverage: **Kafka** bindings are emitted (channel `topic`, operation "
    "`groupId`) because the Kafka binding specification defines real fields. "
    "**NATS** carries exactly one operation field (`queue`), so its binding is "
    "emitted only when a queue group is configured — a stanza carrying nothing but "
    "`bindingVersion` is noise. **Redis** has no binding fields at any level, so no "
    "Redis binding block is emitted at all; a channel's `address` already carries "
    "everything Redis has."
)

_GENERATED_BY_NOTE = (
    "Generated by `varco export-asyncapi` from live, registered EventConsumer "
    "instances. A consumer that is never wired to a bus is deliberately absent."
)


def generate_asyncapi(
    consumers: Iterable[EventConsumer] | DIContainer,
    *,
    title: str,
    version: str,
    protocol: str | None = None,
    group_id: str | None = None,
    queue_group: str | None = None,
    servers: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """
    Build an AsyncAPI 3.1.0 document describing every wired consumer.

    Args:
        consumers:   Live ``EventConsumer`` instances, **or** a ``DIContainer``
                     to resolve them from.  Instances that were never
                     ``register_to()``-ed are skipped.
        title:       ``info.title`` of the generated document.
        version:     ``info.version`` — the *application's* version, not the
                     spec's.
        protocol:    Source bus protocol (``"kafka"`` / ``"nats"`` / ``"redis"``)
                     driving binding emission.  ``None`` (default) emits no
                     bindings at all.
        group_id:    Kafka consumer group, emitted as the operation binding's
                     ``groupId``.  Ignored unless ``protocol="kafka"``.
        queue_group: NATS queue group, emitted as the operation binding's
                     ``queue``.  Ignored unless ``protocol="nats"``.
        servers:     Optional ``{name: "protocol://host"}`` mapping.  **No
                     ``servers`` block is emitted by default** — a broker URL is
                     deployment configuration, not source truth, and baking a dev
                     URL into a committed snapshot is precisely the documentation
                     rot the ``--check`` gate exists to prevent (§D-AA2).

    Returns:
        A plain ``dict`` ready for ``json.dumps()``.  Deterministic: channels,
        operations and messages are all emitted in a stable, sorted order so the
        snapshot diff only moves when the wiring moves.

    Raises:
        ValueError: If a ``servers`` entry is not a ``scheme://host`` URL.

    Edge cases:
        - A container with **no** consumer bindings yields a document with empty
          ``channels``/``operations`` rather than raising — an app that wires no
          consumer is describable, just empty.
        - A container binding that cannot be resolved is skipped, never fatal.
        - Two consumers on one channel share a single channel entry and
          contribute one message each.
        - Two *instances* of one class with callable channels produce two
          channels, which is the whole reason generation is runtime.
        - A ``@listen`` registered by event-type **string** (rather than an
          ``Event`` subclass) yields a message with no ``payload`` — there is no
          model to derive a schema from.

    Example::

        doc = generate_asyncapi(container, title="Orders", version="1.0.0",
                                protocol="kafka", group_id="orders-workers")
    """
    instances = _resolve_consumers(consumers)

    document: dict[str, Any] = {
        "asyncapi": ASYNCAPI_VERSION,
        "info": {
            "title": title,
            "version": version,
            "description": f"{_GENERATED_BY_NOTE}\n\n{_BINDING_COVERAGE_NOTE}",
        },
    }

    if servers:
        document["servers"] = {name: _server_object(url) for name, url in sorted(servers.items())}

    channels: dict[str, dict[str, Any]] = {}
    operations: dict[str, dict[str, Any]] = {}
    # address → channel key, so two consumers on one channel share one entry.
    keys_by_address: dict[str, str] = {}

    for consumer in instances:
        if not _is_registered(consumer):
            # Correct behaviour, not an oversight: an unwired consumer describes
            # a subscription that does not exist.
            continue
        for method_name, entry in _listen_entries(consumer):
            address = _resolve_channel(consumer, entry)
            channel_key = keys_by_address.get(address)
            if channel_key is None:
                channel_key = _unique_key(_slug(address), channels)
                keys_by_address[address] = channel_key
                channels[channel_key] = {"address": address, "messages": {}}
                channel_bindings = _channel_bindings(protocol, address)
                if channel_bindings:
                    channels[channel_key]["bindings"] = channel_bindings

            message_key = _message_key(entry.event_type)
            channels[channel_key]["messages"].setdefault(
                message_key, _message_object(entry.event_type)
            )

            operation_key = _unique_key(
                f"{channel_key}.{type(consumer).__name__}.{method_name}", operations
            )
            operation: dict[str, Any] = {
                "action": "receive",
                "channel": {"$ref": f"#/channels/{channel_key}"},
                "messages": [{"$ref": f"#/channels/{channel_key}/messages/{message_key}"}],
            }
            operation_bindings = _operation_bindings(protocol, group_id, queue_group)
            if operation_bindings:
                operation["bindings"] = operation_bindings
            operations[operation_key] = operation

    # Sorted output: the snapshot gate must not churn on dict insertion order,
    # which depends on `inspect.getmembers` and on the caller's consumer order.
    document["channels"] = {key: _sorted_channel(channels[key]) for key in sorted(channels)}
    document["operations"] = {key: operations[key] for key in sorted(operations)}
    return document


# ── Consumer discovery ─────────────────────────────────────────────────────────


def _resolve_consumers(
    source: Iterable[EventConsumer] | DIContainer,
) -> list[EventConsumer]:
    """
    Normalise *source* into a list of consumer instances.

    Args:
        source: An iterable of instances, or a ``DIContainer``.

    Returns:
        The consumer instances, de-duplicated by identity and in a stable order.

    Edge cases:
        - A container binding registered as an already-constructed *instance*
          (``container.provide(consumer, returns=MyConsumer)``) is read straight
          off the binding rather than resolved, because providify would try to
          *call* the instance as a provider.
        - A binding that cannot be resolved (missing dependency, async provider)
          is skipped rather than aborting the whole export — a partially
          describable app is more useful than a traceback.
    """
    if not isinstance(source, DIContainer):
        return list(source)

    resolved: list[EventConsumer] = []
    seen: set[int] = set()
    for binding in source.get_all_bindings(EventConsumer):
        candidate: object | None = getattr(binding, "fn", None)
        if not isinstance(candidate, EventConsumer):
            try:
                candidate = source.get(binding.interface)
            except Exception:  # noqa: BLE001 — see the docstring's edge case
                continue
        if isinstance(candidate, EventConsumer) and id(candidate) not in seen:
            seen.add(id(candidate))
            resolved.append(candidate)
    return resolved


def _is_registered(consumer: EventConsumer) -> bool:
    """
    Report whether *consumer* has been wired to at least one bus.

    ``EventConsumer.register_to()`` lazily creates ``_registered_buses`` (it has
    no ``__init__`` of its own), so its presence *and* non-emptiness is the
    authoritative "this consumer is live" signal.

    Args:
        consumer: The instance to test.

    Returns:
        ``True`` when ``register_to()`` has been called at least once.
    """
    return bool(getattr(consumer, "_registered_buses", None))


def _listen_entries(consumer: EventConsumer) -> list[tuple[str, _ListenEntry]]:
    """
    Collect every ``@listen`` entry on *consumer*, with its method name.

    Args:
        consumer: A live consumer instance.

    Returns:
        ``(method_name, entry)`` pairs, sorted by method name for determinism.
        ``inspect.getmembers`` walks the full MRO, so inherited handlers are
        included — exactly as ``register_to()`` sees them.
    """
    found: list[tuple[str, _ListenEntry]] = []
    for name, method in inspect.getmembers(consumer, predicate=inspect.ismethod):
        entries: list[_ListenEntry] = getattr(method, "__listen_entries__", [])
        found.extend((name, entry) for entry in entries)
    return sorted(found, key=lambda pair: pair[0])


def _resolve_channel(consumer: EventConsumer, entry: _ListenEntry) -> str:
    """
    Resolve an entry's channel against the bound instance.

    Args:
        consumer: The instance the entry belongs to — the ``self`` a callable
                  channel is resolved against.
        entry:    The ``@listen`` metadata.

    Returns:
        The channel address string, exactly as ``register_to()`` computed it.
    """
    channel = entry.channel
    return channel(consumer) if callable(channel) else channel


# ── Document fragments ─────────────────────────────────────────────────────────


def _message_key(event_type: type[Event] | str) -> str:
    """
    Return the message key for an entry's event type.

    Args:
        event_type: An ``Event`` subclass, or the ``__event_type__`` string used
                    by string-based dispatch.

    Returns:
        A key-safe version of the event type name.
    """
    name = event_type.event_type_name() if isinstance(event_type, type) else event_type
    return _slug(name)


def _message_object(event_type: type[Event] | str) -> dict[str, Any]:
    """
    Build the AsyncAPI message object for an entry's event type.

    Args:
        event_type: An ``Event`` subclass, or an event-type string.

    Returns:
        A message object.  ``payload`` is Pydantic's ``model_json_schema()``
        (JSON Schema Draft 2020-12, which AsyncAPI 3.x accepts — research 004
        §2) and is **omitted** for string-based dispatch, where no model exists
        to derive a schema from.
    """
    if isinstance(event_type, type) and issubclass(event_type, Event):
        return {
            "name": event_type.event_type_name(),
            "title": event_type.__name__,
            "payload": event_type.model_json_schema(),
        }
    return {"name": str(event_type)}


def _channel_bindings(protocol: str | None, address: str) -> dict[str, Any]:
    """
    Build the channel-level bindings for *protocol* (§D-AA3).

    Args:
        protocol: The source bus protocol, or ``None``.
        address:  The channel address — the Kafka topic name.

    Returns:
        ``{"kafka": {...}}`` for Kafka, and an empty dict for every other
        protocol: NATS has no channel-level fields and Redis has none at all.
    """
    if protocol == "kafka":
        return {"kafka": {"topic": address, "bindingVersion": _KAFKA_BINDING_VERSION}}
    return {}


def _operation_bindings(
    protocol: str | None, group_id: str | None, queue_group: str | None
) -> dict[str, Any]:
    """
    Build the operation-level bindings for *protocol* (§D-AA3).

    Args:
        protocol:    The source bus protocol, or ``None``.
        group_id:    Kafka consumer group.
        queue_group: NATS queue group.

    Returns:
        A bindings mapping, or an empty dict.  Each binding is emitted only when
        it would carry a real field — never a lone ``bindingVersion``, which
        communicates nothing while still needing to be maintained.
    """
    if protocol == "kafka" and group_id:
        return {"kafka": {"groupId": group_id, "bindingVersion": _KAFKA_BINDING_VERSION}}
    if protocol == "nats" and queue_group:
        return {"nats": {"queue": queue_group, "bindingVersion": _NATS_BINDING_VERSION}}
    return {}


def _server_object(url: str) -> dict[str, str]:
    """
    Split an explicit ``protocol://host`` server URL into an AsyncAPI server.

    Args:
        url: e.g. ``"kafka://broker.example.com:9092"``.

    Returns:
        ``{"host": ..., "protocol": ...}``, plus ``"pathname"`` when the URL has
        a path (a NATS or MQTT server may).

    Raises:
        ValueError: If the scheme or the host is missing — a half-specified
                    server is worse than none, because it lands in a committed
                    snapshot.
    """
    parts = urlsplit(url)
    if not parts.scheme or not parts.netloc:
        raise ValueError(f"server URL {url!r} must be of the form 'protocol://host[:port]'")
    server = {"host": parts.netloc, "protocol": parts.scheme}
    if parts.path and parts.path != "/":
        server["pathname"] = parts.path
    return server


# ── Key helpers ────────────────────────────────────────────────────────────────


def _slug(value: str) -> str:
    """
    Make *value* safe to use as a document key and a JSON-Pointer segment.

    Args:
        value: A channel address or event type name.

    Returns:
        The value with every character outside ``[A-Za-z0-9_.-]`` replaced by
        ``_``.  ``CHANNEL_ALL`` (``"*"``) becomes ``"_"``, which is why
        ``_unique_key`` exists.

    Edge cases:
        - An empty input yields ``"_"``: a key must be non-empty.
    """
    return _KEY_SAFE_RE.sub("_", value) or "_"


def _unique_key(candidate: str, taken: Mapping[str, Any]) -> str:
    """
    Return *candidate*, suffixed if necessary so it is absent from *taken*.

    Args:
        candidate: The preferred key.
        taken:     The mapping the key must not collide within.

    Returns:
        ``candidate``, or ``candidate-2``, ``candidate-3``, … on collision.
        Deterministic given a deterministic iteration order, which is why
        ``_listen_entries`` sorts.
    """
    if candidate not in taken:
        return candidate
    suffix = 2
    while f"{candidate}-{suffix}" in taken:
        suffix += 1
    return f"{candidate}-{suffix}"


def _sorted_channel(channel: dict[str, Any]) -> dict[str, Any]:
    """
    Return *channel* with its ``messages`` mapping key-sorted.

    Args:
        channel: A built channel object.

    Returns:
        The same object with deterministic message ordering, so the committed
        snapshot does not churn on handler discovery order.
    """
    channel["messages"] = {key: channel["messages"][key] for key in sorted(channel["messages"])}
    return channel


__all__ = ["ASYNCAPI_VERSION", "generate_asyncapi"]
