"""
models.py
=========
Domain model for the blog post entity in the Beanie/MongoDB example.

``Post`` is a pure-Python ``@dataclass`` subclass of ``DomainModel``.
No ODM imports, no Beanie Document — the ``varco_beanie`` backend generates
the full Beanie Document class at startup via ``BeanieModelFactory`` from the
field annotations and ``FieldHint`` / ``PrimaryKey`` metadata decorators.

Key design choices
------------------
- ``pk`` uses ``PKStrategy.UUID_AUTO`` — the factory injects ``default_factory=uuid4``
  onto the generated Beanie ``id`` field, so a UUID is assigned before the
  first ``save()`` without a round-trip to MongoDB.
- ``created_at`` / ``updated_at`` are inherited from ``AuditedDomainModel``
  as ``init=False`` fields.  The mapper sets them via ``object.__setattr__``
  during INSERT/UPDATE.  The service's ``_prepare_for_create`` hook also
  stamps them Python-side so values are available immediately after ``save()``.
- ``author`` is a plain ``str`` (display name, not a foreign key) so the
  example stays self-contained — no ``User`` collection needed.
- ``content`` maps to a TEXT-equivalent in MongoDB — stored as a plain ``str``
  with no length limit enforced at the ODM layer (MongoDB is schemaless).

DESIGN: Pure DomainModel with no Beanie imports
    ✅ Model is backend-agnostic — the same class could be used with SA, Beanie, etc.
    ✅ No ODM code in tests — instantiate ``Post(title=..., content=..., author=...)``
       directly without an asyncio event loop.
    ✅ ``BeanieModelFactory`` auto-generates the Beanie Document class from the
       annotations — no manual Pydantic Field() declarations needed.
    ❌ No back-references or Beanie link fields — those require ``BeanieDocRegistry.get()``
       customisation with ``Meta.customize`` (acceptable here).

Thread safety:  ✅ Dataclass — no shared mutable state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PrimaryKey, PKStrategy, pk_field
from varco_core.model import AuditedDomainModel


@dataclass
class Post(AuditedDomainModel):
    """
    Blog post domain entity backed by MongoDB.

    The Beanie Document class is generated automatically by ``BeanieModelFactory``
    at application startup from the field annotations below.

    Inherits from ``AuditedDomainModel`` which provides:
        created_at: Set once on INSERT by the mapper.  ``init=False``.
        updated_at: Refreshed on every UPDATE by the mapper.  ``init=False``.

    Fields:
        pk:       UUID primary key, auto-generated before INSERT.
        title:    Post headline, max 255 chars.
        content:  Post body text — stored as a plain string in MongoDB.
        author:   Author display name, max 100 chars.

    Edge cases:
        - ``pk`` is auto-assigned by the Beanie Document ``id`` field
          (``default_factory=uuid4``) before ``save()`` — it is available
          immediately without a SELECT round-trip.
        - ``created_at`` / ``updated_at`` are ``None`` until the entity is
          persisted.  ``PostRead`` expects real datetimes, so the service
          stamps them before ``save()`` via ``_prepare_for_create``.
        - MongoDB does not enforce ``max_length`` constraints at the driver level —
          ``FieldHint(max_length=...)`` is advisory metadata for documentation
          and future validator integration.

    Thread safety:  ✅ Dataclass — no shared state.
    Async safety:   ✅ Pure value object.
    """

    # Primary key — UUID auto-generated by the Beanie Document id field.
    # pk_field(init=False) means the constructor does not accept pk as an
    # argument — the mapper reads it back from the ODM object after save().
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    # Business fields — FieldHint() carries field metadata for BeanieModelFactory.
    # max_length is advisory only on MongoDB (no DDL enforcement).
    title: Annotated[str, FieldHint(max_length=255)] = ""
    content: Annotated[str, FieldHint()] = ""
    author: Annotated[str, FieldHint(max_length=100)] = ""

    class Meta:
        # MongoDB collection name.
        # Prefixed with "ex10_" to avoid collisions if other examples use
        # the same database instance.
        table = "ex10_posts"


__all__ = ["Post"]
