"""
models
======
Domain model for the ``Document`` entity used in the Casbin policy example.

``Document`` uses ``AuditedDomainModel`` for automatic timestamp management
(``created_at`` / ``updated_at``).  Authorization is entirely handled by the
Casbin policy engine — not by an ``owner_id`` field — so this model is
simpler than the grant-based-authz example.

DESIGN: no ``owner_id`` on the model
    In this example authorization comes from the RBAC policy engine, not
    from document ownership.  Adding ``owner_id`` would mix two authorization
    strategies and obscure the Casbin teaching point.

    ✅ Model stays clean — only domain data, no authorization artefacts.
    ✅ RBAC is the single source of truth for access control.
    ❌ Cannot express per-document ownership without extending the model
       and adding custom ABAC matchers — a deliberate simplification.

Thread safety:  ✅ Dataclass — each instance is independent, no shared state.
Async safety:   ✅ Pure value object — no I/O.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated
from uuid import UUID

from varco_core.meta import FieldHint, PKStrategy, PrimaryKey, pk_field
from varco_core.model import AuditedDomainModel


@dataclass
class Document(AuditedDomainModel):
    """
    Document entity — the core resource managed by this example.

    Fields:
        pk:         UUID, auto-generated by the repository on first ``save()``.
        title:      Document title, max 255 chars.
        content:    Document body (freeform text).
        created_at: UTC timestamp set on first ``save()`` — inherited.
        updated_at: UTC timestamp refreshed on every ``save()`` — inherited.

    Edge cases:
        - ``pk`` is ``None`` until persisted.
        - ``created_at`` / ``updated_at`` are ``None`` until after the first
          ``save()`` — the assembler must not read them before save returns.

    Thread safety:  ✅ Dataclass — immutable after construction.
    Async safety:   ✅ Pure value object — no I/O.
    """

    # Primary key — UUID auto-generated by the repository on first save().
    # ``pk_field()`` marks this as ``init=False`` so the constructor does not
    # accept it; the repository stamps it via ``object.__setattr__``.
    pk: Annotated[UUID, PrimaryKey(PKStrategy.UUID_AUTO)] = pk_field()

    title: Annotated[str, FieldHint(max_length=255)] = ""
    content: str = ""

    class Meta:
        # Table name — informational; in-memory store doesn't use it.
        table = "documents"


__all__ = ["Document"]
